grouped_html = [
    ['aemails.org.html', 'aerex.eu.html', 'aevesdk3.com.html', 'afro-pari.com.html', 'ahamconsumerconnections.org.html', 'ahbynmkkmnfu.shop.html', 'ai-center.online.html', 'aigner-haag.at.html', 'akashinime.guru.html', 'alessiofalcone.it.html', 'alhasanfoundation.in.html', 'alileime.org.html', 'alimarkets.com.html', 'alimarkets.it.html', 'alinahoivatiimi.com.html', 'alinahoivatiimi.net.html', 'aliper.com.html', 'aliper.it.html', 'alisupermercati.com.html', 'alisupermercato.eu.html', 'almacom-gmbh.eu.html', 'almighty-jezuz.com.html', 'alwin.ltd.uk.html', 'amdac-carmichael.com.html', 'angangintl.com.html', 'annabeodog.xyz.html', 'aotvqsuprqnb.shop.html', 'apco911.com.html', 'apimco.link.html', 'app-go88s.biz.html', 'appleclub.tech.html', 'approvedfast.com.html', 'apps-foundry.com.html', 'arabianchemicalterminals.com.html', 'arbetslivsmuseer.se.html', 'arcadeeurope.com.html', 'argonfinancial.com.html', 'arttoy.cc.html', 'asahibeerusa.com.html', 'asd.net.html', 'asiafundspace.com.html', 'audreysweets.xyz.html'],
    ['aitoka.shop.html', 'amcun3.online.html', 'amcun9.online.html', 'amt-avaluos.online.html', 'anzald.com.html', 'artfay.tv.html', 'ashfordcenter.world.html', 'astroservice.top.html', 'authologic.io.html', 'babubasics.co.uk.html', 'babubasics.com.html', 'celestialkeepsakes.com.html', 'championdirect.store.html', 'eonfibre.net.html', 'golf-saint-cyprien.com.html', 'paddygower.com.html', 'scalingspecialists.com.html', 'sodearif.com.html', 'stratalaser.com.html', 'thisisthefuckingnews.com.html'],
    ['alphamaterialsinc.com.html', 'americanairless.com.html', 'angelvisiontravel.com.html', 'brakeditorial.com.html', 'citizensagainstsextrafficking.org.html', 'crazyadsclimber.com.html', 'doughansonconstruction.com.html', 'fidexor.com.html', 'grantiah.com.html', 'harotzu.com.html', 'jandptrucking.com.html', 'keepmybooks.pro.html', 'keepmybooks.services.html', 'moneyweedwives.com.html', 'moneyweedwives.show.html', 'nounsbverbn.com.html', 'ordfld.com.html', 'pvcgs.org.html', 'pyramidelectric.us.html', 'rovics.com.html'],
    ['amordevoltarapido.com.br.html'],
    ['amyqnliycusz.shop.html'],
    ['atyourlevel.online.html'],
    ['badlandsconcerts.com.html', 'badlandslightfest.com.html', 'columbiahouse.ca.html', 'concoursparcscanada.ca.html', 'couplesdash.com.html', 'datewithdice.com.html', 'dudecheck.com.html', 'fmdistilled.com.html', 'globewayimmigration.com.html', 'ilovestubbs.com.html', 'membranereactor.com.html', 'nobullheating.com.html', 'rootsbluesbarbecue.com.html', 'soultosolesoundspa.com.html', 'templarsnotary.com.html', 'wifipresspad.com.html'],
]
